=== FearlessGames/spaced/server/src/main/resources/xsd/cooldowns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="base.xsd"/>
	<xs:element name="list">
	  <xs:complexType>
		 <xs:sequence>
			<xs:element ref="cooldown" maxOccurs="unbounded" minOccurs="0"/>
		 </xs:sequence>
	  </xs:complexType>
	</xs:element>
	<xs:element name="cooldown">
	  <xs:complexType>
		 <xs:sequence>
			<xs:element type="uuidType" name="pk"/>
			<xs:element ref="name"/>
			<xs:element ref="cooldownTime" />
		 </xs:sequence>
	  </xs:complexType>
	</xs:element>

	<xs:element name="name">
	  <xs:simpleType>
		 <xs:restriction base="xs:string">
			 <xs:pattern value="[A-Za-z0-9-]+"/>
		 </xs:restriction>
	  </xs:simpleType>
	</xs:element>

	<xs:element name="cooldownTime">
	  <xs:simpleType>
		 <xs:restriction base="xs:decimal" />
	  </xs:simpleType>
	</xs:element>

</xs:schema>

=== FearlessGames/spaced/server/resources/cooldowns.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/cooldowns.xsd">
	<cooldown>
		<pk>22e57ada-9bd9-4ff5-ac8a-9e07d9f4f3f7</pk>
		<name>melee-cooldown</name>
		<cooldownTime>0.5</cooldownTime>
	</cooldown>
	<cooldown>
		<pk>e3ad25aa-efc1-4537-a1a3-9e07d9f532e0</pk>
		<name>missile-cooldown</name>
		<cooldownTime>1.5</cooldownTime>
	</cooldown>
	<cooldown>
		<pk>7a2cf96e-1314-47f6-bf18-9e07d9f850f8</pk>
		<name>mental-cooldown</name>
		<cooldownTime>2.5</cooldownTime>
	</cooldown>
	<cooldown>
		<pk>4fa5731b-54b1-4eda-919d-9eee3f9c349b</pk>
		<name>dot-cooldown</name>
		<cooldownTime>10</cooldownTime>
	</cooldown>
	<cooldown>
		<pk>9e58863f-321f-42ad-be23-9f4ed35792e5</pk>
		<name>on-use-cooldown</name>
		<cooldownTime>0.5</cooldownTime>
	</cooldown>
</list>
