=== FearlessGames/spaced/server/src/main/resources/xsd/mobtemplates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
			  xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="base.xsd"/>

	<xs:element name="list" type="listType"/>


	<xs:complexType name="spellBookType">
		<xs:sequence>
			<xs:element type="spellType" name="spell" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="mobType">
		<xs:sequence>
			<xs:element type="xs:string" name="name"/>
			<xs:element type="uuidType" name="pk"/>
			<xs:element type="appearanceType" name="appearance"/>
			<xs:element type="referenceType" name="creatureType"/>
			<xs:element type="referenceType" name="faction"/>
			<xs:element type="brainType" name="brainTemplate"/>
			<xs:element type="lootType" name="lootTemplate"/>
			<xs:element type="spellBookType" name="spellBook" minOccurs="0"/>
			<xs:element type="xs:integer" name="stamina"/>
			<xs:element type="xs:integer" name="maxShield"/>
			<xs:element type="xs:double" name="shieldRecovery"/>
			<xs:element type="xs:double" name="coolRate"/>
			<xs:element type="transportationModesType" name="transportationModes"/>
			<xs:group ref="brainParamsGroup" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element type="equipmentType" name="equippedItems" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="listType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element type="mobType" name="mob"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="lootType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="reference"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="brainType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="reference"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="transportationModesType" mixed="true">
		<xs:sequence maxOccurs="unbounded">
			<xs:group ref="transportModesGroup"/>
		</xs:sequence>
		<xs:attribute name="class"/>
	</xs:complexType>
	<xs:group name="transportModesGroup">
		<xs:choice>
			<xs:element name="WALK" type="xs:double"/>
			<xs:element name="RUN" type="xs:double"/>
			<xs:element name="CHARGE" type="xs:double"/>
			<xs:element name="FLY" type="xs:double"/>
		</xs:choice>
	</xs:group>
	<xs:group name="brainParamsGroup">
		<xs:sequence>
			<xs:group ref="brainParamGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="brainParamGroup">
		<xs:choice>
			<xs:element type="whisperMessageType" name="whisperMessage"/>
			<xs:element type="xs:string" name="scriptPath"/>
			<xs:element type="forSaleType" name="itemTypesForSale"/>
			<xs:element type="xs:boolean" name="moveToTarget"/>
			<xs:element type="xs:boolean" name="lookAtTarget"/>
			<xs:element type="xs:integer" name="proximityAggroDistance"/>
			<xs:element type="xs:integer" name="socialAggroDistance"/>
		</xs:choice>
	</xs:group>
	<xs:complexType name="whisperMessageType">
		<xs:sequence>
			<xs:element name="pk" type="uuidType"/>
			<xs:element name="message" type="xs:string"/>
			<xs:element name="whisperDistance" type="xs:double"/>
			<xs:element name="whisperTimeout" type="xs:long"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="forSaleType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="item" type="referenceType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="equipmentType">
		<xs:sequence>
			<xs:element type="equipmentElement" name="entry" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="equipmentElement">
		<xs:sequence>
			<xs:element name="equipmentSlot" type="slotType"/>
			<xs:element name="item" type="referenceType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="slotType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MAIN_HAND"/>
			<xs:enumeration value="OFF_HAND"/>
			<xs:enumeration value="HEAD"/>
			<xs:enumeration value="CHEST"/>
			<xs:enumeration value="LEGS"/>
			<xs:enumeration value="FEET"/>
			<xs:enumeration value="BACK"/>
			<xs:enumeration value="HAND"/>
			<xs:enumeration value="UTILITY"/>
			<xs:enumeration value="BAG_SLOT"/>
			<xs:enumeration value="LEFT_WRIST"/>
			<xs:enumeration value="RIGHT_WRIST"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== FearlessGames/spaced/server/src/main/resources/mobtemplates.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/mobtemplates.xsd">
	<mob>
		<name>Lt. Kroker</name>
		<pk>b0340b1a-86fd-48d4-b479-9db86049f3ec</pk>
		<appearance>
			<modelName>models/mobs/noob_town_guard.xmo</modelName>
			<portraitName>icon_dummy</portraitName>
		</appearance>
		<creatureType reference="humanoid"/>
		<faction reference="players"/>
		<brainTemplate reference="whisper-brain"/>
		<lootTemplate reference="empty loot"/>
		<spellBook>
			<spell reference="Lazor blast"/>
		</spellBook>
		<stamina>4</stamina>
		<maxShield>4</maxShield>
		<shieldRecovery>1</shieldRecovery>
		<coolRate>5</coolRate>
		<transportationModes class="enum-map">
			<WALK>2.5</WALK>
			<RUN>6.0</RUN>
		</transportationModes>
		<whisperMessage>
			<pk>fc28c9ae-f9ca-473f-ae7d-9f943f0c3663</pk>
			<message>Greetings stowaway, you think you could sneak by me? If you could help my dillusioned friend Watto in
				the town shop downstairs to your right I might let you off the hook.
			</message>
			<whisperDistance>10.0</whisperDistance>
			<whisperTimeout>90000</whisperTimeout>
		</whisperMessage>
	</mob>

	<mob>
		<name>Capt. Wardson</name>
		<!-- Add titles "Head of Endiku guard" -->
		<pk>53306911-42c1-45ef-b7e9-9f78148a7637</pk>
		<appearance>
			<modelName>/models/mobs/noob_town_guard_mk3_red.xmo</modelName>
			<portraitName>icon_player</portraitName>
		</appearance>
		<creatureType reference="humanoid"/>
		<faction reference="players"/>
		<brainTemplate reference="attacking-aggro-proximitywhisper-roaming-brain"/>
		<lootTemplate reference="empty loot"/>
		<spellBook>
			<spell reference="Lazor blast"/>
		</spellBook>
		<stamina>25</stamina>
		<maxShield>200</maxShield>
		<shieldRecovery>3</shieldRecovery>
		<coolRate>3</coolRate>
		<transportationModes class="enum-map">
			<WALK>2.5</WALK>
			<RUN>6.0</RUN>
		</transportationModes>
		<whisperMessage>
			<pk>914ea204-a4ba-484c-90bb-9f943f0c47dd</pk>
			<message>$NAME$! Kill all borg pigs for me please!</message>
			<whisperDistance>10.0</whisperDistance>
			<whisperTimeout>300000</whisperTimeout>
		</whisperMessage>
	</mob>

	<mob>
		<name>Endiku town guard</name>
		<pk>c5f95bd2-24bd-46c2-859f-9f78149264b5</pk>
		<appearance>
			<modelName>models/mobs/noob_town_guard.xmo</modelName>
			<portraitName>icon_player</portraitName>
		</appearance>
		<creatureType reference="humanoid"/>
		<faction reference="players"/>
		<brainTemplate reference="attacking-aggro-roaming-brain"/>
		<lootTemplate reference="empty loot"/>
		<spellBook>
			<spell reference="Lazor blast"/>
		</spellBook>
		<stamina>18</stamina>
		<maxShield>150</maxShield>
		<shieldRecovery>3</shieldRecovery>
		<coolRate>3</coolRate>
		<transportationModes class="enum-map">
			<WALK>2.5</WALK>
			<RUN>6.0</RUN>
		</transportationModes>
	</mob>

	<mob>
		<name>Endiku town patrol</name>
		<pk>b73a8e0b-4fb3-4083-8dfe-9f79158da2c3</pk>
		<appearance>
			<modelName>models/mobs/noob_town_guard.xmo</modelName>
			<portraitName>icon_player</portraitName>
		</appearance>
		<creatureType reference="humanoid"/>
		<faction reference="players"/>
		<brainTemplate reference="attacking-aggro-patrolling-brain"/>
		<lootTemplate reference="empty loot"/>
		<spellBook>
			<spell reference="Lazor blast"/>
		</spellBook>
		<stamina>18</stamina>
		<maxShield>150</maxShield>
		<shieldRecovery>3</shieldRecovery>
		<coolRate>3</coolRate>
		<transportationModes class="enum-map">
			<WALK>2.5</WALK>
			<RUN>6.0</RUN>
		</transportationModes>
	</mob>

	<mob>
		<name>Wattor</name>
		<pk>5559ce47-cfe6-411a-9254-9f52d92cfafd</pk>
		<appearance>
			<modelName>models/mobs/noob_town_greeter.xmo</modelName>
			<portraitName>icon_dummy</portraitName>
		</appearance>
		<creatureType reference="humanoid"/>
		<faction reference="players"/>
		<brainTemplate reference="whisper-vendor-brain"/>
		<lootTemplate reference="empty loot"/>
		<spellBook>
			<spell reference="Lazor blast"/>
		</spellBook>
		<stamina>35</stamina>
		<maxShield>300</maxShield>
		<shieldRecovery>4</shieldRecovery>
		<coolRate>1</coolRate>
		<transportationModes class="enum-map">
			<WALK>1.5</WALK>
			<RUN>2.5</RUN>
		</transportationModes>
		<whisperMessage>
			<pk>ec176547-9f4c-47bd-ae32-9f943f999b8c</pk>
			<message>Hi $NAME$! Please help me find my lost cousin! He is an inventor working on a prototype jetpack when
				he crashed in the wilderness. The distress call came close the lake up north. You might need to purchase
				some of my goods to help you on your journey though. Hoho!
			</message>
			<whisperDistance>10.0</whisperDistance>
			<whisperTimeout>200000</whisperTimeout>
		</whisperMessage>
		<itemTypesForSale>
			<item reference="Bucket of Popplers"/>
			<item reference="Can of Slurm"/>
			<item reference="Simple Wrist Computer"/>
			<item reference="Tri Claw"/>
			<item reference="Beginners shield generator"/>
		</itemTypesForSale>
	</mob>

	<mob>
		<name>Scott Michaels</name>
		<pk>00f9e2f2-1e31-4c5e-a1a4-9f944012b0e9</pk>
		<appearance>
			<modelName>models/players/player_male.xmo</modelName>
			<portraitName>icon_manager</portraitName>
		</appearance>
		<creatureType reference="humanoid"/>
		<faction reference="dcs"/>
		<brainTemplate reference="scripted-patrolling-brain"/>
		<lootTemplate reference="scott-michaels-loot"/>
		<spellBook>
			<spell>
				<pk>83181fa4-2402-470c-9749-9d9f39873cc3</pk>
				<name>Pocket rocket</name>
				<castTime>1500</castTime>
				<effects>
					<projectile>
						<pk>640d61a3-dca2-4837-9111-9d9f39873cc3</pk>
						<resourceName>projectiles/lazor_blast</resourceName>
						<school>PHYSICAL</school>
						<speed>300.0</speed>
						<impactEffects>
							<damageSchoolEffect>
								<pk>b2aa3559-8cbf-46a9-a09e-9d9f39873cc3</pk>
								<resourceName>abilities/lazor_blast</resourceName>
								<school>LIGHT</school>
								<range>
									<start>52</start>
									<end>94</end>
								</range>
							</damageSchoolEffect>
						</impactEffects>
					</projectile>
				</effects>
				<school>LIGHT</school>
				<targetingType>TARGET</targetingType>
				<requiresHostileTarget>true</requiresHostileTarget>
				<cancelOnMove>true</cancelOnMove>
				<ranges>
					<start>0</start>
					<end>42</end>
				</ranges>
				<effectResource>abilities/lazor_blast</effectResource>
				<heatContribution>5</heatContribution>
			</spell>
			<spell>
				<pk>053be621-9bf3-4f56-a763-9d9f39873cc8</pk>
				<name>Hard blow</name>
				<castTime>100</castTime>
				<effects>
					<damageSchoolEffect>
						<pk>0b138642-57a3-427e-b5ee-9d9f39873cc8</pk>
						<resourceName>abilities/melee</resourceName>
						<school>PHYSICAL</school>
						<range>
							<start>120</start>
							<end>270</end>
						</range>
					</damageSchoolEffect>
				</effects>
				<school>PHYSICAL</school>
				<targetingType>TARGET</targetingType>
				<requiresHostileTarget>true</requiresHostileTarget>
				<cancelOnMove>false</cancelOnMove>
				<ranges>
					<start>0</start>
					<end>6</end>
				</ranges>
				<effectResource>abilities/melee</effectResource>
				<heatContribution>1</heatContribution>
			</spell>
		</spellBook>
		<stamina>100</stamina>
		<maxShield>1000</maxShield>
		<shieldRecovery>1</shieldRecovery>
		<coolRate>1.5</coolRate>
		<transportationModes class="enum-map">
			<WALK>2.5</WALK>
			<RUN>7.0</RUN>
		</transportationModes>
		<scriptPath>mobs/ai/scott_michaels.lua</scriptPath>
	</mob>

	<mob>
		<name>DCS soldier</name>
		<pk>3e29f432-5287-4d25-905e-a01608765fb4</pk>
		<appearance>
			<modelName>models/mobs/noob_town_guard.xmo</modelName>
			<portraitName>icon_player</portraitName>
		</appearance>
		<creatureType reference="humanoid"/>
		<faction reference="dcs"/>
		<brainTemplate reference="attacking-aggro-roaming-brain"/>
		<lootTemplate reference="empty loot"/>
		<spellBook>
			<spell reference="Strike"/>
		</spellBook>
		<stamina>18</stamina>
		<maxShield>150</maxShield>
		<shieldRecovery>3</shieldRecovery>
		<coolRate>3</coolRate>
		<transportationModes class="enum-map">
			<WALK>2.5</WALK>
			<RUN>6.0</RUN>
		</transportationModes>
	</mob>

	<mob>
		<name>Small Patrol ship</name>
		<pk>0167bac7-32d1-4993-8ae6-a02723273013</pk>
		<appearance>
			<modelName>/props/vehicles/flying/small/s-11/s-11.xmo</modelName>
			<portraitName>icon_mysteriouscrate</portraitName>
		</appearance>
		<creatureType reference="mechanical"/>
		<faction reference="dcs"/>
		<brainTemplate reference="attacking-aggro-patrolling-brain"/>
		<lootTemplate reference="empty loot"/>
		<spellBook>
			<spell reference="Lazor blast"/>
		</spellBook>
		<stamina>100</stamina>
		<maxShield>5000</maxShield>
		<shieldRecovery>5</shieldRecovery>
		<coolRate>3</coolRate>
		<transportationModes class="enum-map">
			<FLY>10.0</FLY>
		</transportationModes>
	</mob>

	<mob>
		<name>Aron Murphy</name>
		<pk>a0a15515-a056-4c96-9b0b-a06d8eb7ae7e</pk>
		<appearance>
			<modelName>models/mobs/human_male_basic.xmo</modelName>
			<portraitName>icon_dummy</portraitName>
		</appearance>
		<creatureType reference="humanoid"/>
		<faction reference="players"/>
		<brainTemplate reference="attacking-vendor-brain"/>
		<lootTemplate reference="empty loot"/>
		<spellBook>
			<spell reference="Strike"/>
		</spellBook>
		<stamina>35</stamina>
		<maxShield>300</maxShield>
		<shieldRecovery>4</shieldRecovery>

		<coolRate>1</coolRate>
		<transportationModes class="enum-map">
			<WALK>3.5</WALK>
			<RUN>5.5</RUN>
		</transportationModes>
		<whisperMessage>
			<pk>03a7d38c-91f4-434b-85df-a06d8ed18ddc</pk>
			<message>Not used</message>
			<whisperDistance>5.0</whisperDistance>
			<whisperTimeout>180000</whisperTimeout>
		</whisperMessage>
